### ISSUE TITLE
Cannot read property 'profiler' of undefined

### ISSUE THREAD

**Issue by stolinski** [ultimatejs/tracker-react#12]
On v1.0.2 Meteor v1.3 beta 12

No matter what I do, I can't get rid of this error. Using my own code, or starting fresh and using the exact code from here https://github.com/ultimatejs/tracker-react#implementation

**Comment by ykshev** [comment]
Version 1.0.0 works well.
Have a look: https://github.com/ultimatejs/tracker-react/issues/11

**Comment by queso** [comment]
Looks like it has to do with the profiler added in the commits here: https://github.com/ultimatejs/tracker-react/commit/aec91d8320da1a9a714b07f476c71630a85a64ce#diff-f9c684e75cdabbc10ce141bc30755c8eR64.

**Comment by stolinski** [comment]
@tastemeru downgrading fixed the issue.

**Comment by queso** [comment]
Need to get some testing on this repo :)

**Comment by D1no** [comment]
All correct - please stick to v1.0.3 - it was a dumb, neglected undefined check that I missed while rushing to wrap it up. And the bug does not show always (commonJS quirk). I'll pull the profiler out into a separate package to not bloat production code and have room for more advanced extensions which I need.

Right now, as long Meteor is 1.3 is in Beta, it's some trying out - also regarding Tracker behavior. So please use TrackerReact consciously - as soon the dust settles on the Meteor 1.3 testing story, this bug bull whip will end.

**Comment by queso** [comment]
No worries, I am loving this library. Hoping MDG gives it a serious look.

We all love being on the bleeding edge :laughing:

**Comment by D1no** [comment]
We'll see ;) From what I learned in the past three years is that MDG is rather apath on such not-home-grown things... so I'll safe my energy; even more thanks to you for your involvement josh
