### ISSUE TITLE
Unable to get this package to work... no errors, just empty array.

### ISSUE THREAD

**Issue by onedr0p** [ultimatejs/tracker-react#13]
Using `ultimatejs:tracker-react@1.0.2` on `Meteor 1.3 Beta 12`

I am having trouble getting this to work. I get no errors and in the render... `console.log(this._unreadNotifsCount());` only outputs `[]` (empty array) to the console. I have verified that there are indeed documents in this collection that should be returned.

I have included the code below, please let me know if I'm doing something wrong.

Client-side in my component:

``` js
import React, { Component } from 'react';
import { TrackerReactMixin } from 'meteor/ultimatejs:tracker-react';

@TrackerReactMixin
export default class AppNav extends Component {
  constructor() {
    super();
    this.state = {
      name: Meteor.user().profile.firstName + ' ' + Meteor.user().profile.lastName,
      subscription: {
        unreadNotifs: Meteor.subscribe('unreadNotifs')
      }
    };
  }

  componentWillUnmount() {
    this.state.subscription.unreadNotifs.stop();
  }

  _unreadNotifsCount() {
    return UserNotifications.find({}).fetch();
  }

  render() {
    console.log(this._unreadNotifsCount());
    return (
      <div>Testing subscription</div>
    );
  }
}
```

Server-side publication:

``` js
Meteor.publish('unreadNotifs', function() {
  return UserNotifications.find({
    $and: [{
      to: this.userId,
      dismissed: false
    }]
  });
});
```

**Edit:** I have also verified my publication is working via meteortoys. I am subscribed... but it looks like I cannot access my subscription via:

``` js
  _unreadNotifsCount() {
    return UserNotifications.find({}).fetch();
  }
```

Thanks :+1:

**Comment by D1no** [comment]
Meteor does not support Decorators right now. Please use the compose Method
class AppNav extends TrackerReact(Component) 

otherwise everything else looks correct

**Comment by onedr0p** [comment]
That component I mentioned above is part of my nav-bar. The strange this is that when I go to another route via a nav-bar link it updates and shows the documents, it just doesn't work on the initial page load. So it seems like meteor can handle the decorator (or at least partially)?

Anyways, I'll try it out the other method you mentioned tomorrow and see if I can get it to function right. Thanks.

**Comment by D1no** [comment]
That's because the component is probably re-mounted. It's not an reactive update. 

Would be nice if decorator support is coming. But as far as I know, it's not on stage 2 yet in the tc39 committee - so that it doesn't throw a compile error is probably a bug of the ecmascript package.

**Comment by onedr0p** [comment]
Thanks for the explanation, I was really confused :) I'll prolly go with the react-mixin package if that works, it seems cleaner.

You may want to mention in the docs (in the decorators section) that decorators aren't support yet in meteor, because it reads as if it's supported.

**Edit** apologies, I see you have it in the docs, just not in the decorator section.

**Comment by D1no** [comment]
I do, but good suggestion
- [ ] Readme: Emphasize in Decorator Section that Meteor does currently not support those.

**Comment by onedr0p** [comment]
Alright confirmed using ReactMixin package everything is working now.

Thanks again for all the help! Closing this issue.
