### ISSUE TITLE
Cannot read property 'profiler' of undefined

### ISSUE THREAD

**Issue by janka** [ultimatejs/tracker-react#14]
Hi.

When creating a component, if I do NOT add an empty opt object like this:
`class App extends TrackerReact(React.Component, {}) {`
...I get a:

```
TypeError: Cannot read property 'profiler' of undefined
    at Object.TrackerReactLog [as log] (profiler.js:11)
...
```

**Comment by janka** [comment]
BTW, I'm on 1.3-beta.12 :-)

**Comment by D1no** [comment]
Should be fixed . Update to TrackerReact version 1.0.3

I am waiting now for the first meteor 1.3 rc

**Comment by janka** [comment]
Ok, now I see the old #12
