### ISSUE TITLE
[Question] es6 style class syntax?

### ISSUE THREAD

**Issue by awei01** [ultimatejs/tracker-react#2]
Just out of curiosity, was there a decision behind mixin pattern instead of using an extensible es6 class?

e.g:

```
class TrackerReactComponent extends React.Component {
    componentWillMount() {
          this.autorunRender();
    }
    ...
    autorunRender() {
        ...
    }

}
```

**Comment by faceyspacey** [comment]
To appear uniform with Meteor's initial getMeteorData mixin approach. 

I will be releasing Meteor.Component soon whose interface will be more like that, i.e. no visible mixins.

**Comment by awei01** [comment]
ok, cool. thx for explanation.

**Comment by D1no** [comment]
@faceyspacey any update on this?

**Comment by D1no** [comment]
@awei01 TrackerReact (v1.0.0^) supports now ES6/7 Composition and Mixin/Decorators. See the example in the readme (make sure to use Meteor 1.3 and track-react v1.0.0^ to use the composition style):
https://github.com/ultimatejs/tracker-react/blob/master/README.md#example
