### ISSUE TITLE
componentWillReceive props, etc

### ISSUE THREAD

**Issue by faceyspacey** [ultimatejs/tracker-react#22]
I've been using plain react + redux and realized that _TrackerReact_ doesn't get the benefit of such lifecycle handlers as `componentWillReceiveProps` which is central to exposing declarative interfaces, even when internally within a component you have to do a few imperative things, such as with animations. 

TrackerReact could be upgraded to do what Redux and basically everything else does where a parent component maintains the state and passes new props to the child component. So instead of calling `forceUpdate` on the target component, we do it on the invisible parent component pass the reactive data down as props to the original component. 

It's been a while since I've worked with this, so I could be missing something. Anyway, just an idea to throw out there. Perhaps given the "automatic reactivity" it in fact doesn't make sense. @D1no ? How do you do things in replace of `componentWillReceiveProps` now? Use `componentDidUpdate` (which I presume will still be called after `forceUpdate`) and manually check if the values are different, and then perhaps trigger an animation?

**Comment by D1no** [comment]
With the automatic reactivity of TrackerReact I indeed think, it doesn't make sense. TrackerReact should be used as a top level component already; so if one would wish to check for incoming (reactive) props, simply do so on level below. At this point, I am pretty happy how it is.
