### ISSUE TITLE
Where would you subscribe to collections?

### ISSUE THREAD

**Issue by dbismut** [ultimatejs/tracker-react#4]
That's probably a dumb question, but where would you subscribe to collections?

**Comment by awei01** [comment]
I'd assume this is largely left up to the developer. You could do it outside the component entirely or you could do it from within a method defined in your component. If you have a use case, I could give you a better suggestion. But, just off the top of my head, here's a simple example:

```
MySearchComponent = React.createClass({
    mixins: [TrackerReact],
    getResults() {
         var query = this.state && this.state.query;
         if (!query) {
              return;
         }
         var sub = Meteor.subscribe('myPublication', query);
         var cursor = MyCollection.find({ name: query });
         return cursor.fetch();
    }
    render() {
        var results = this.getResults() || [];
        return (
             <div>
                  <input type="text" onInput={ this.handleInput }/>
                  { 
                       results.map(// iterate through results)
                  }
             </div>              
        ) 
    }
    handleInput(event) {
         this.setState({ query: event.target.value });
    }
});


```

**Comment by faceyspacey** [comment]
I agree, there's a mismatch of sorts between performing Meteor subscriptions and React components. 

...The place I would put the `subscribe` call is in `componentWillMount` and stop it in `componentWillUnmount` or use `Meteor.startup`.

The above example has the side-effect of stopping and re-running the subscription any time the query itself reactively updates.

**Comment by awei01** [comment]
@faceyspacey: Valid point on the re-running of subscription. But, how would you otherwise implement this situation? Suppose the use case is searching through users by username and that you have many user records? Wouldn't you have to stop/restart the subscription (in Blaze or React)? I'm just wondering if I'm overlooking something myself.

**Comment by faceyspacey** [comment]
@awei01 i agree. ..im gonna release methods for autoruns and subscriptions in components for just those needs. Right now there is one autorun for all of the `render` method. it should be a separate one. 

...for now, in `componentWillMount` create your own autorun (dependent on whatever data sources it needs) and make the subscription there; and then stop that autorun on `componentWillUnmount`.

**Comment by dbismut** [comment]
Thanks for all this, much appreciated.

**Comment by awei01** [comment]
@faceyspacey: good idea.

**Comment by D1no** [comment]
An example was added. Re-running subscriptions has no effect, unless they were stopped before (Mount / UnMount). Don't un/subscribe on the data-serving methods themself.

See the example in the readme (make sure to use Meteor 1.3 and track-react v1.0.0^ to use the composition style):
https://github.com/ultimatejs/tracker-react/blob/master/README.md#example

Please re-open if there is a remaining issue.
