### ISSUE TITLE
'return' outside of function error

### ISSUE THREAD

**Issue by ghost** [ultimatejs/tracker-react#7]
Thanks for writing this mixin!

Line 2 (`if (Meteor.isServer) return;`) seems to be causing issues using METEOR@1.3-modules-beta.5 

```
Errors prevented startup:

While processing files with ecmascript (for target web.browser):
packages/ultimatejs:tracker-react/tracker-react-mixin.js:2:21: /packages/ultimatejs:tracker-react/tracker-react-mixin.js: 'return' outside of function (2:21)
```

**Comment by ghost** [comment]
This existing PR would probably fix this error: https://github.com/ultimatejs/tracker-react/pull/6/files

**Comment by D1no** [comment]
This issue is fixed now in Beta6 - allowed again to have top level returns (though they are not ES6 compliant).
https://github.com/meteor/meteor/issues/6144

**Comment by ghost** [comment]
Confirmed. This error message is no longer present with Meteor beta 6.

tracker-react is still not loading data for me, but I'm going to play with it more to see if it's my code or if the linked PR is still needed. I have a feeling that the linked PR is still needed because I also had to upgrade my subscriptions and queries to use `global.FooCollection` to get them to work with Meteor 1.3 beta.
