### ISSUE TITLE
Meteor 1.3 - Re-Render not triggered on react from npm

### ISSUE THREAD

**Issue by D1no** [ultimatejs/tracker-react#8]
When using Meteor 1.3 and using react from npm with react-mixin, changes are not re-rendered. Reactive changes are visible after i.e. a page reload.

Any fix for this? Here is a reproduction Repo:
https://github.com/D1no/TrackerReact-Meteor1.3/blob/master/client/main.jsx

You also mentioned a while back you are working on a component-style implementation. Any update on that?

Thx and best regards
Dino

**Comment by faceyspacey** [comment]
Did the pull request fix your initial issue regarding changes being re-rendered? 

Also as for the higher order component implementation in place of the mixin, basically we can copy the approach laid out here:

https://github.com/meteor/react-packages/issues/169

**Comment by D1no** [comment]
If you mean
https://github.com/ultimatejs/tracker-react/pull/6
no, that is (was) unrelated. 

I did not fully follow the thread - I am not sure what the status is. I think it probably has to do with an incompatibility with react .15 (from npm). 

If you clone the repo, just check yourself with

```
meteor update --release 1.3-modules-beta.8
```

(or recent release at the time)

in web console

``` js
Mongo.Collection.get("tasks").insert({title: "Test Title", text: "A dummy text."});
```

Seems like the invalidation does not work. Data only shows on reload.
