### ISSUE TITLE
Will subscription will be auto rerun and stop on unmount?

### ISSUE THREAD

**Issue by zhaoyao91** [ultimatejs/tracker-react#9]
Will subscription will be auto rerun and stop on unmount? with `ReactMeteorData`, we make sub in `getMeteorData` function, but where should I sub data with `tracker-react`?

**Comment by D1no** [comment]
@zhaoyao91 You should subscribe to data separately (similar to the use of Blaze) on the `constructor()` (in ES5 = `componentWillMount()`) level and unsubscribe in the `componentWillUnmount()` method.

See the example in the readme (make sure to use Meteor 1.3 and track-react v1.0.0^ to use the composition style):
https://github.com/ultimatejs/tracker-react/blob/master/README.md#example

**Comment by zhaoyao91** [comment]
by using ReactMeteorData, we sub in getMeteorData, and all sub will be maintain and auto rerun when the state and props change. it's convenient.

**Comment by D1no** [comment]
I am not following, what do you suggest? The purpose of TrackerReact is imo to particularly unfreeze data calls from one single method like getMeteorData() does.

Setting up subscriptions to methods is here analogous to the component life cycle management. Though it could be done, putting magic into stopping subscriptions seems to rather hinder functional clarity and the ability to pass subscriptions around. (Gladly take Arguments)

Generally, if you have too many higher level subscriptions in one component, it is always a good idea to break it up into a composition of a few.

**Comment by zhaoyao91** [comment]
thanks for your talk, I will re-consider the problems.
